-- MySQL Script generated by MySQL Workbench
-- Mon Jun 27 16:06:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_art_ativa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_art_ativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_art_ativa` DEFAULT CHARACTER SET utf8 ;
USE `db_art_ativa` ;

-- -----------------------------------------------------
-- Table `db_art_ativa`.`TB_CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_art_ativa`.`TB_CATEGORIA` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NOT NULL,
  `DESCRICAO` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_art_ativa`.`TB_USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_art_ativa`.`TB_USUARIO` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NOT NULL,
  `USUARIO` VARCHAR(255) NOT NULL,
  `SENHA` VARCHAR(255) NOT NULL,
  `FOTO` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `USUARIO_UNIQUE` (`USUARIO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_art_ativa`.`TB_PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_art_ativa`.`TB_PRODUTOS` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(255) NOT NULL,
  `DESCRICAO` VARCHAR(600) NOT NULL,
  `PRECO` DECIMAL(10,2) NOT NULL,
  `QUANTIDADE` INT NOT NULL,
  `FOTO` VARCHAR(255) NULL,
  `TB_USUARIO_ID` BIGINT NOT NULL,
  `TB_CATEGORIA_ID` BIGINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_TB_PRODUTOS_TB_USUARIO1_idx` (`TB_USUARIO_ID` ASC) VISIBLE,
  INDEX `fk_TB_PRODUTOS_TB_CATEGORIA1_idx` (`TB_CATEGORIA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_TB_PRODUTOS_TB_USUARIO1`
    FOREIGN KEY (`TB_USUARIO_ID`)
    REFERENCES `db_art_ativa`.`TB_USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_PRODUTOS_TB_CATEGORIA1`
    FOREIGN KEY (`TB_CATEGORIA_ID`)
    REFERENCES `db_art_ativa`.`TB_CATEGORIA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `db_art_ativa` ;

-- -----------------------------------------------------
--  routine1
-- -----------------------------------------------------

DELIMITER $$
USE `db_art_ativa`$$
$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
